### PR TITLE
Cash-Register

### PR DESCRIPTION
**Pull request by WALWALASAFI**
🔹🔹                                                                               
This is the cash register  app that will return change to the customer based on the price of the item. the amount of cash provided by the customer, and the amount of cash in the cash drawer. You'll also need to show different messages to the user in different scenarios, such as when the customer provides too little cash or when the cash drawer doesn't have enough to issue the correct change.

### CODE REVIEW

**Comment by ahzamir** [comment]
@WALWALASAFI 

- Your project has linters issues and I can not see your partner's feedback!

**Comment by WALWALASAFI** [comment]
@ZohalMirkhel

**Comment by ZohalMirkhel** [comment]
Dear @WALWALASAFI, I reviewed your project and found a few issues. Firstly, there are some linter errors. Additionally, the cash in the drawer is not being displayed. Although your HTML code is clean, there is still room for improvement by removing the extra lines between the closing tags of the div elements.
Thank you so much!

**Comment by WALWALASAFI** [comment]
@ahzamir 
Hi dear sir,
i hope ur fine. 
the linters errors have been finished,  i was working on it more than one week. 
and thanks a bunch that you hopefully encouraged me, and give me power of being motivational.

**Review by ahzamir — APPROVED** [review]
### Hi @WALWALASAFI 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- I can see your pull-request is from `main` to `feature` and also your default branch is `cash` branch which is wrong:
  - Change your default branch to `development` and also edit your pull-request from `development` to `cash` and then directly merge it.
  
- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
